config/routes.rb
Rails.application.routes.draw do
  
  root "authors#index"
  resources :authors do
    resources :books
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :books
  validates :name, presence: true
  validates_format_of :contact_no, :with => /[0-9]{10}/, allow_blank: true
  before_create do
    self.name = name.capitalize 
  end
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
  
  validates :name,:published_at, presence: true
  before_create do
    self.name = name.capitalize 
  end
  after_create do
    Author.where(id: author_id).update("no_of_books = no_of_books + 1")
  end
  after_destroy do
    Author.where(id: author_id).update("no_of_books = no_of_books - 1")
  end

  BOOK_TYPE = {"Novel" => 0, "Short Stories" => 1, "Others" => 2}
end

app/models/idea.rb
class Idea < ApplicationRecord
end

app/models/quote.rb
class Quote < ApplicationRecord
  validates :name, presence: true
  scope :ordered, -> { order(id: :desc) }
  after_create_commit -> { broadcast_prepend_to "quotes" }
  after_update_commit -> { broadcast_replace_to "quotes" }
  after_destroy_commit -> { broadcast_remove_to "quotes" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
    @authors = Author.all
  end

  def show
    @author = Author.find(params[:id])
  end

  def new
    @author = Author.new
  end

  def create
    @author = Author.new(author_params)
    if @author.save
      respond_to do |format|
        format.html { redirect_to authors_path, notice: "Author was successfully created." }
        format.turbo_stream
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @author = Author.find(params[:id])
  end

  def update
    @author = Author.find(params[:id])

    if @author.update(author_params)
      redirect_to authors_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @author = Author.find(params[:id])
    @author.books.destroy_all
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_path, notice: "Author was successfully destroyed." }
      format.turbo_stream
    end
  end

  private
    def author_params
      params.require(:author).permit(:name,:email,:contact_no,:address)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def new 
    @author = Author.find(params[:author_id])
  end

  def create
    @author = Author.find(params[:author_id])
    @book = @author.books.create(book_params)
    AuthorMailer.mailsend(@author)
    respond_to do |format|
      format.html { redirect_to author_path(@author), notice: "Book was successfully created." }
      format.turbo_stream
    end
  end

  def show
    @author = Author.find(params[:author_id])
    @book = @author.books.find(params[:id])
  end

  def edit
    @author = Author.find(params[:author_id])
    @book = @author.books.find(params[:id])
  end

  def update
    @author = Author.find(params[:author_id])
    @book = @author.books.find(params[:id])

    if @book.update(book_params)
      redirect_to author_path(@author)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @author = Author.find(params[:author_id])
    @book = @author.books.find(params[:id])
    @book.destroy
    respond_to do |format|
      format.html { redirect_to author_path(@author), notice: "Book was successfully destroyed." }
      format.turbo_stream
    end
  end

  private
  def book_params
    params.require(:book).permit(:name,:book_type,:published_at)
  end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :set_idea, only: %i[ show edit update destroy ]

  # GET /ideas or /ideas.json
  def index
    @ideas = Idea.all
  end

  # GET /ideas/1 or /ideas/1.json
  def show
  end

  # GET /ideas/new
  def new
    @idea = Idea.new
  end

  # GET /ideas/1/edit
  def edit
  end

  # POST /ideas or /ideas.json
  def create
    @idea = Idea.new(idea_params)

    respond_to do |format|
      if @idea.save
        format.html { redirect_to idea_url(@idea), notice: "Idea was successfully created." }
        format.json { render :show, status: :created, location: @idea }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ideas/1 or /ideas/1.json
  def update
    respond_to do |format|
      if @idea.update(idea_params)
        format.html { redirect_to idea_url(@idea), notice: "Idea was successfully updated." }
        format.json { render :show, status: :ok, location: @idea }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ideas/1 or /ideas/1.json
  def destroy
    @idea.destroy

    respond_to do |format|
      format.html { redirect_to ideas_url, notice: "Idea was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_idea
      @idea = Idea.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def idea_params
      params.require(:idea).permit(:name, :description, :picture)
    end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController

  def index
    @quotes = Quote.ordered
  end

  def show
    @quote = Quote.find(params[:id])
  end

  def new
    @quote = Quote.new
  end

  def create
    @quote = Quote.new(quote_params)

    if @quote.save
      respond_to do |format|
        format.html { redirect_to quotes_path, notice: "Quote was successfully created." }
        format.turbo_stream
      end
    else
      render :new
    end
  end

  def edit
    @quote = Quote.find(params[:id])
  end

  def update
    @quote = Quote.find(params[:id])

    if @quote.update(quote_params)
      redirect_to quotes_path, notice: "Quote was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @quote = Quote.find(params[:id])
    @quote.destroy

    respond_to do |format|
      format.html { redirect_to quotes_path, notice: "Quote was successfully destroyed." }
      format.turbo_stream
    end
  end

  private
  def quote_params
    params.require(:quote).permit(:name)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/authors/_author.html.erb
<%= turbo_frame_tag author do %>
  <div class="author">
    <table>
      <tr>
        <td>
          <%= link_to author.name, author_path(author)%>
        </td>
        <td>
          <%= button_to "Edit", edit_author_path(author) , method:"get" ,class:"btn btn-warning" %>
        </td>
        <td>
        <%= button_to "Destroy", author_path(author), method: "delete", confirm: "Are you sure?",class:"btn btn-danger" %>
        </td>
      </tr>
    </table>
  </div>
<% end %>

app/views/authors/_form.html.erb
<%= form_with model: @author do |form| %>
  <div>
    <%= form.label :author %><br>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :email%><br>
    <%= form.text_field :email %>
  </div>
  <div>
    <%= form.label :contact_no%><br>
    <%= form.text_field :contact_no %>
  </div>
  <div>
    <%= form.label :address%><br>
    <%= form.text_field :address %>
  </div>
  <br>
  <button class="btn btn-success" onclick="form.submit">Submit</button>
<% end %>

app/views/authors/create.turbo_stream.erb
<%= turbo_stream.append "authors" do %>
  <%= render @author %>
<% end %>

<%= turbo_stream.update Author.new, "" %>

app/views/authors/destroy.turbo_stream.erb
<%= turbo_stream.remove @author %>

app/views/authors/edit.html.erb
<div>
  <h1>Edit Authors Details</h1>
  <%= turbo_frame_tag @author do %>
    <%= render "form", author: @author %>
  <% end %>
</div>

app/views/authors/index.html.erb
<div>
  <h1>Authors List</h1>
  <%= turbo_frame_tag "authors" do %>
    <%= render @authors %>
  <% end %>
  <br>
  <%= button_to "New Author", new_author_path , method:"get" ,class:"btn btn-success", data: { turbo_frame: dom_id(Author.new)} %>
  <%= turbo_frame_tag Author.new %>
</div>

app/views/authors/new.html.erb
<div>
  <h1>New Author Details</h1>
  <%= turbo_frame_tag @author do %>
    <%= render "form", author: @author %>
  <% end %>
</div>

app/views/authors/show.html.erb
<%= turbo_frame_tag @author do %>
<div>
  <h2><%= @author.name %></h2>
  <p><%= @author.address %> &#44; <%= @author.email %> &#44; <%= @author.contact_no %></p>
  <ul>
  <%= turbo_frame_tag "books" do %>
    <% @author.books.each do |book| %>
      <%= turbo_frame_tag book do %>
      <table>
        <tr>
          <td>
            <h4><%= book.name %></h4> 
            <p>published at <%= book.published_at %></p>
          </td>
          <td>
            <%= button_to "Edit", edit_author_book_path(:author_id => @author, :id => book), method:"get" ,class:"btn btn-warning" %>
          </td>
          <td>
            <%= button_to "Destroy", author_book_path(:author_id => @author, :id => book), method: "delete", confirm: "Are you sure?", class:"btn btn-danger" %>
          </td>
        </tr>
      </table>
      <% end %>
    <% end %>
  <% end %>
  </ul>
  <div id="button-part">
    <div>
      <%= button_to "Add Book", new_author_book_path(@author), method:"get", class:"btn btn-primary", data: { turbo_frame: dom_id(Book.new)} %>
    </div>
    <div>
      <%= button_to "Back", authors_path, method:"get", class:"btn btn-primary" %>
    </div>
    <%= turbo_frame_tag Book.new %>
  </div>
</div>
<% end %>

app/views/books/_book.html.erb
<%= turbo_frame_tag book do %>
  <div class="book">
    <table>
      <tr>
        <td>
          <%= link_to book.name, author_book_path(:author_id => @author,:id => book) %>
        </td>
        <td>
          <%= button_to "Edit", edit_author_book_path(:author_id => @author, :id => @book), method:"get" ,class:"btn btn-warning" %>
        </td>
        <td>
          <%= button_to "Destroy", author_book_path(:author_id => @author, :id => @book), method: "delete", confirm: "Are you sure?", class:"btn btn-danger" %>
        </td>
      </tr>
    </table>
  </div>
<% end %>

app/views/books/_form.html.erb
<% @option = params["action"] == "edit" ? @book : @author.books.build %>

<%= form_with model:[@author,@option] do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </div>
  <br>
  <div>
    <%= form.label :'select type' %><br>
    <%= form.select :book_type, Book::BOOK_TYPE %>
  </div>
  <br>
  <div>
    <%= form.label :published_at%><br>
    <%= form.date_field :published_at %>
  </div>
  <br>
  <div>
    <button class="btn btn-success" onclick="form.submit">Submit</button>
  </div>
<% end %>

app/views/books/create.turbo_stream.erb
<%= turbo_stream.append "books" do %>
  <%= turbo_frame_tag @book do %>
    <table>
      <tr>
        <td>
          <h2><%= @book.name %></h2> 
          <p>published at <%= @book.published_at %></p>
        </td>
        <td>
          <%= button_to "Edit", edit_author_book_path(:author_id => @author, :id => @book), method:"get" ,class:"btn btn-warning" %>
        </td>
        <td>
          <%= button_to "Destroy", author_book_path(:author_id => @author, :id => @book), method: "delete", confirm: "Are you sure?", class:"btn btn-danger" %>
        </td>
      </tr>
    </table>
    <% end %>
<% end %>

<%= turbo_stream.update Book.new, "" %>

app/views/books/destroy.turbo_stream.erb
<%= turbo_stream.remove @book %>

app/views/books/edit.html.erb
<div>
  <h1>Edit Book Details</h1>
  <%= turbo_frame_tag @book do %>
    <%= render "form", author:@author , book:@book %>
  <% end %>
</div>

app/views/books/new.html.erb
<div>
  <h1>New Book Details</h1>
  <%= turbo_frame_tag "new_book" do %>
    <%= render "form", author: @author %>
  <% end %>
</div>

app/views/books/show.html.erb
# <div>
#   <div>
#     <h2><%=@book.name%></h2> 
#     <p>published at <%= @book.published_at%></p>
#   </div>
#   <div id="button-part">
#     <div>
#       <%= button_to "Edit", edit_author_book_path(:author_id => @author, :id => @book), method:"get" ,class:"btn btn-warning" %>
#     </div>
#     <div>
#       <%= button_to "Destroy", author_book_path(:author_id => @author, :id => @book), method: "delete", confirm: "Are you sure?", class:"btn btn-danger" %>
#     </div>
#   </div>
# </div>

app/views/ideas/_form.html.erb
<%= form_with(model: idea) do |form| %>
  <% if idea.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

      <ul>
        <% idea.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :picture, style: "display: block" %>
    <%= form.text_field :picture %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/ideas/_idea.html.erb
<div id="<%= dom_id idea %>">
  <p>
    <strong>Name:</strong>
    <%= idea.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= idea.description %>
  </p>

  <p>
    <strong>Picture:</strong>
    <%= idea.picture %>
  </p>

</div>

app/views/ideas/edit.html.erb
<h1>Editing idea</h1>

<%= render "form", idea: @idea %>

<br>

<div>
  <%= link_to "Show this idea", @idea %> |
  <%= link_to "Back to ideas", ideas_path %>
</div>

app/views/ideas/index.html.erb
<p style="color: green"><%= notice %></p>



<div id="ideas">
  <h1>Ideas</h1>
  <table>
     <% @ideas.each do |idea| %>
     <tr>
        <td style="width:20rem;"><%= render idea %></td>
        <td style="width:20rem;"><%= link_to "Show this idea", idea %></td>
    </tr>
    <% end %>
  </table>
  <%= link_to "New idea", new_idea_path %>
</div>

app/views/ideas/new.html.erb
<h1>New idea</h1>

<%= render "form", idea: @idea %>

<br>

<div>
  <%= link_to "Back to ideas", ideas_path %>
</div>

app/views/ideas/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @idea %>

<div>
  <%= link_to "Edit this idea", edit_idea_path(@idea) %> |
  <%= link_to "Back to ideas", ideas_path %>

  <%= button_to "Destroy this idea", @idea, method: :delete %>
</div>

app/views/layouts/_flash.html.erb
<% flash.each do |flash_type, message| %>
  <div
    class="flash__message"
    data-controller="removals"
    data-action="animationend->removals#remove"
  >
    <%= message %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" integrity="sha512-PgQMlq+nqFLV4ylk1gwUOgm6CtIIXkKwaIHp/PAIWHzig/lKZSEGKEysh0TCVbHJXCLN7WetD8TFecIky75ZfQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <!-- Popper JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
    <title>TestApp</title>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <div class="container-fluid main_menu">
      <div class="row">
        <div class="col-md-10 col-12 mx-auto">
          <nav class="navbar navbar-expand-lg ">
            <a class="navbar-brand">Test App</i></a>
          </nav>
        </div>
      </div>
    </div>
    <div id="mid-part">
      <%= yield %>
    </div>
  </body>
  <footer>
    <p>Created with ❤️ by Souvick Mondal</p>
  </footer>
</html>

app/views/quotes/_form.html.erb
<%= form_with model: @quote do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit  %>
  </div>
<% end %>

app/views/quotes/_quote.html.erb
<%= turbo_frame_tag quote do %>
  <div class="quote">
    <table>
      <tr>
        <td>
          <%= link_to quote.name, quote_path(quote), data: { turbo_frame: "_top" }%>
        </td>
        <td>
          <div class="quote__actions">
            <%= button_to "Delete",
                          quote_path(quote),
                          method: :delete,
                          class: "btn btn--light" %>
        <td>
        <td>
          <div class="quote__actions">
            <%= button_to "Edit",
                        edit_quote_path(quote),
                        method:"get",
                        class: "btn btn--light" %>
          </div>
        </td>
      </tr>
    </table>
  </div>
<% end %>

app/views/quotes/create.turbo_stream.erb
<%= turbo_stream.prepend "quotes" do %>
  <%= render @quote %>
<% end %>

<%= turbo_stream.update Quote.new, "" %>

app/views/quotes/destroy.turbo_stream.erb
<%= turbo_stream.remove @quote %>

app/views/quotes/edit.html.erb
<main class="container">
  <%= link_to "Back to quote", quote_path(@quote) %>

  <div class="header">
    <h1>Edit quote</h1>
  </div>
  <%= turbo_frame_tag @quote do %>
     <%= render "form", quote: @quote %>
  <% end %>
</main>

app/views/quotes/index.html.erb
<%= turbo_stream_from "quotes" %>
<div class="container">
  <div class="header">
    <h1>Quotes</h1>
    <%= link_to "New quote",
                new_quote_path,
                class: "btn btn--primary",
                data: { turbo_frame: dom_id(Quote.new) } %>
  </div>

  <%= turbo_frame_tag Quote.new %>

  <%= turbo_frame_tag "quotes" do %>
    <%= render @quotes %>
  <% end %>
</div>

app/views/quotes/new.html.erb
<main class="container">
  <%= link_to sanitize("&larr; Back to quotes"), quotes_path %>

  <div class="header">
    <h1>New quote</h1>
  </div>

  <%= turbo_frame_tag @quote do %>
    <%= render "form", quote: @quote %>
  <% end %>
</main>

app/views/quotes/show.html.erb
<h2><%= @quote.name %></h2> 