user_app/config/routes.rb
Rails.application.routes.draw do

  root "users#index"
  #get "/users", to: "users#index"
  #get "/users/:id", to: "users#show"
  resources :users
  get "users/get_user_details/:id" => "users#get_user_details", as: :get_user_details_user

end

user_app/app/models/user.rb
class User < ApplicationRecord
end

user_app/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to @user
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    redirect_to "users#index", status: :see_other
  end

  def get_user_details
    @user = User.find(params[:id])
  end

  private
    def user_params
      params.require(:user).permit(:name, :address, :age, :email, :status)
    end
end

user_app/app/helpers/users_helper.rb
module UsersHelper
end

user_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UserApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

user_app/app/views/users/_form.html.erb
<%= form_with model: @user do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :age %><br>
    <%= form.number_field :age %>
  </div>
   <div>
    <%= form.label :email %><br>
    <%= form.text_field :email %>
  </div>
  <div>
    <%= form.label :status %><br>
    <%= form.check_box :status %>
  </div>
  <div>
    <%= form.label :address %><br>
    <%= form.text_area :address %>
  </div>
  <div>
    <%= form.submit  %>
  </div>
<% end %>

user_app/app/views/users/edit.html.erb
<h1>Edit User Details</h1>

<%= render "form", user: @user %>

user_app/app/views/users/get_user_details.html.erb
<h1><%= @user.name %></h1>

<p>Age : <%= @user.age %></p>

<p>Email : <%= @user.email %></p>

<p>Status : <%= @user.status ? "active" : "inactive" %></p>

<p>Address : <%= @user.address %></p>

user_app/app/views/users/index.html.erb
<h1>User Details</h1>

<ul>
  <% @users.each do |user| %>
    <li>
      <%= link_to user.name, get_user_details_user_path(user)%>
    </li>
  <% end %>
</ul>

<%= link_to "New User", new_user_path %>

user_app/app/views/users/new.html.erb
<h1>New User Details</h1>

<%= render "form", user: @user %>

user_app/app/views/users/show.html.erb
<h1><%= @user.name %></h1>

<p>Age : <%= @user.age %></p>

<p>Email : <%= @user.email %></p>

<p>Status : <%= @user.status ? "active" : "inactive" %></p>

<p>Address : <%= @user.address %></p>

<ul>
  <li><%= link_to "Edit", edit_user_path(@user) %></li>

  <li><%= link_to "Destroy", user_path(@user), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  }%></li>
</ul>